### ISSUE TITLE
New botkit-storage-dynamodb

### ISSUE THREAD

**Issue by sebasibarguen** [howdyai/botkit-storage-base#2]
Hi howdyai team, I'm not sure if this is the right form to communicate this, but didn't find another way. I created storage driver for DynamoDB. 

https://github.com/designengine/botkit-storage-dynamodb

**Comment by anonrig** [comment]
I receive a `Page not found` error. Is the link correct?

**Comment by joshuahoover** [comment]
I know this is closed but it's one of the top search results for Botkit and DynamoDB. I created this module: https://www.npmjs.com/package/botkit-storage-dynamodb 

I could use some help getting tests to pass since I'm new to Node and async code. That said, I'm using this module in production. It's working great for me.
